








































































































































                                               <script>
window.HUSHMAIL={loginForm:function(c){var d={};var f=document.getElementById("login-form");f&&(f.onsubmit=b);function b(){if(f.elements.hush_username.value==""){f.elements.hush_username.focus();return false}if(f.elements.bookmark.checked){var i=f.elements.hush_username.value;if(i.indexOf("@")<0){i+="@hushmail.com"}i=i.replace(/[^A-Za-z0-9-_@\.]/g,"");var g="https://www.hushmail.com/"+i;var h="Sign in to Hushmail ("+i+")";if(document.all&&window.external){window.external.AddFavorite(g,h)}}}function e(){c.emailAddress&&f&&(f.elements.hush_username.value=c.emailAddress)}function a(){f&&f.elements.hush_username&&f.elements.hush_username.focus()}d.populate=e;d.focus=a;return d},request:function(a){var c={};function d(){var f=b("hush_username");var e=b("hush_domain");if(f&&f.indexOf("@")!==-1){return f}else{if(e){return f+"@"+e}}return null}function b(f){var e=RegExp("[?&]"+f+"=([^&]*)").exec(window.location.search);return e&&decodeURIComponent(e[1].replace(/\+/g," "))}c.getEmailAddress=d;return c},upgradeLinks:function(a){var b={};function c(){if(!a.emailAddress){return}var e=["upgrade-to-premium","upgrade-to-desktop","upgrade-to-forms"];for(var f in e){var d=document.getElementById(e[f]);if(d&&d.tagName==="A"){d.href+=d.href.indexOf("?")>=0?"&":"?";d.href+="hush_username="+a.emailAddress}else{if(d&&d.tagName==="FORM"){input=document.createElement("INPUT");input.type="hidden";input.name="hush_username";input.value=a.emailAddress;d.appendChild(input)}}}}b.init=c;return b},businessAccountCreationForm:function(c){var d={};var e=document.getElementById("business-account-creation-form");e&&(e.onsubmit=b);function b(){if(e.elements.hush_username.value.indexOf("@")==-1){document.getElementById("error_business_account_creation_username").style.display="block";e.elements.hush_username.focus();return false}return true}function a(){e&&e.elements.hush_username&&e.elements.hush_username.focus()}d.focus=a;return d},contactForm:function(k){var f={};var d;var i;function j(){if(document.getElementById("contact-form")){d=document.getElementById("contact-form");if(d.elements.hush_subject){d.elements.hush_subject.onchange=h}d.onsubmit=a}if(document.getElementById("hush_contact-success")){if(document.location.search.indexOf("?success=1")===0){document.getElementById("hush_contact-success").style.display="block"}}}function h(){var l=d.elements.hush_subject.value;var m=document.getElementById(l);if(i){i.style.display="none"}if(m){m.style.display="block";i=m}var n=document.getElementById("contact-form-fields-and-buttons");if(n){n.style.display=(l==="Please close my free Hushmail account"?"none":"block")}}function a(){b();g();c();e()}function e(){var l=d.elements.Comments;if(l){l.value="\n\n"+l.value}}function g(){var m=d.elements.hush_subject;var l=d.elements.name;if(m&&m.value==""&&l&&l.value!=""){d.elements.hush_subject.value=d.elements.name.value}}function c(){var m=d.elements["Hushmail username"];var l=d.elements["Hushmail domain"];if(m&&l){if(m.value.indexOf("@")<0){m.value+="@"+l.value}l.name=""}}function b(){var l=d.elements.hush_sender;if(l&&l.value==""){var n=d.elements["Hushmail username"];var m=d.elements["Hushmail domain"];if(n&&m){d.elements.hush_sender.value=n.value+"@"+m.value}}}f.init=j;return f},partners:function(){var a={};function b(){if(document.getElementById("hush_partner-noaccess")&&document.getElementById("hush_partner-signout")){if(document.location.search.indexOf("?no_access=1")===0){document.getElementById("hush_partner-noaccess").style.display="block"}if(document.location.search.indexOf("?sign_out=1")===0){document.getElementById("hush_partner-signout").style.display="block"}}}a.init=b;return a},web:function(b){var d={};var h,f,a,c,e;function g(){c=HUSHMAIL.request();h=HUSHMAIL.loginForm({emailAddress:c.getEmailAddress()});h.populate();h.focus();a=HUSHMAIL.contactForm({});a.init();f=HUSHMAIL.businessAccountCreationForm();f.focus();upgradeLinks=HUSHMAIL.upgradeLinks({emailAddress:c.getEmailAddress()});upgradeLinks.init();e=HUSHMAIL.partners();e.init()}g();return d}};

</script>
